version: "3.7"

services:
  php:
    container_name: php
    build:
      context: ./
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        PW: ${PW:-docker}
        USER: ${USER:-docker}
        AWS_KEY: ${AWS_KEY}
        AWS_SECRET: ${AWS_SECRET}
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
