service: app

provider:
    name: aws
    region: us-east-1
    environment:
        BREF_PING_DISABLE: 1

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: api.php
        description: ''
        runtime: php-82-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
#            - httpApi: '*'
            - httpApi:
                  method: GET
                  path: /cep/{cep}
            - schedule:
                  rate: rate(5 minutes)
                  input:
                      warmer: true
    hello:
        handler: hello.php
        description: ''
        runtime: php-82

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
